### ISSUE TITLE
Implementation of this design

### ISSUE THREAD

**Issue by Aljeshka** [ultraembedded/core_ddr3_controller#2]
Did someone actually manage to implement this design?

Simple AXI instructions that work with Xilinx MIG dont work here at all. Like bvalid never goes high. Or you want to read from DDR? Have fun waiting for arready. Whats up with that? How was the core tested? There is no detail about it

**Comment by Aljeshka** [comment]
NOP commands work fine though ;)

**Comment by ultraembedded** [comment]
You haven't given me enough info to go on here.
I have booted Linux on a SoC using this DDR controller. It seems reliable, even though running Linux will be hammering the DDR.
I have recently put some fixes in so maybe try again?
